config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  get 'tweets' => 'tweets#index'
  get 'tweets/new' => 'tweets#new'
  post 'tweets' => 'tweets#create'
  get 'users/:id' => 'users#show'
  delete 'tweets/:id' => 'tweets#destroy'
  get 'tweets/:id/edit' => 'tweets#edit'
  patch 'tweets/:id' => 'tweets#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user, foreign_key: "user_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, foreign_key: "id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController< ApplicationController
    def index
        @tweets=Tweet.all.order(updated_at: "DESC").page(params[:page]).per(5)
    end

    def new
        unless user_signed_in?
            redirect_to action: :index      
        end
    end

    def create

        Tweet.create(
            title:params[:title],
            comment:params[:note],
            user_id:current_user.id
        )
    end

    def destroy
        deletetweet=Tweet.find(params[:id])
        if current_user.id == deletetweet.user_id
            deletetweet.destroy
        end       
    end
    
    def edit
        @tweet=Tweet.find(params[:id])     
    end
    
    def update
        edittweet=Tweet.find(params[:id])
        if current_user.id == edittweet.user_id
            edittweet.update(title:params[:title],comment:params[:note])
        end       
    end
    

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @tweets=Tweet.where(user_id: current_user.id).order(updated_at: "DESC").page(params[:page]).per(5)
        @nickname=current_user.nickname
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workdir</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/">PicTweet</a></h1>
      <% if user_signed_in? %>
      <div class="user_nav grid-6">
        <span><%= current_user.nickname %>
          <ul class="user__info">
            <li>
              <a href="/users/<%= current_user.id %>">マイページ</a>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </span>
        <a class="post" href="/tweets/new">投稿する</a>
      </div>
     <% else %>
     <div class="grid-6">
      <%= link_to "ログイン", new_user_session_path, class: 'post' %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
    </div>
    <% end %>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>


  <footer>
      <p>
        Copyright PicTweet 20XX.
      </p>
    </footer>
</html>

app/views/tweets/create.html.erb
<div class="contents row" >
    <div class="success">
        <h3>投稿が完了しました。</h3>
        <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row" >
    <div class="success">
        <h3>削除が完了しました。</h3>
        <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row" >
    <%= form_tag("/tweets/#{@tweet.id}", method: :patch)  do %>
        <h3>編集する</h3>
        <input placeholder="Title" type="text" name="title" value="<%= @tweet.title%>">
        <textarea placeholder="Note" type="text" cols="30" rows="10" name="note"><%= @tweet.comment%></textarea>
        <input type="submit" value="SENT">
    <% end %>
</div>

app/views/tweets/index.html.erb
<% @tweets.each do |tweet| %>
    <div class="contents row">
        <div class="content_post" style="background-color:#ccc;">
            <% if user_signed_in? && current_user.id == tweet.user_id%>
                <div class="more">
                    <span><%= image_tag 'arrow_top.png'%></span>
                    <ul class="more_list">
                        <li>
                            <%= link_to '編集' , "tweets/#{tweet.id}/edit" ,method: :get %>
                        </li>
                        <li>
                            <%= link_to '削除' , "tweets/#{tweet.id}" ,method: :delete %>
                        </li>
                    </ul>
                </div>
            <%end%>
            <%= simple_format(tweet.title) %>
            <span class="name"><%= tweet.comment%></div>
        </div>
    </div>
<% end %>
<div class="contents row" >
    <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row" >
    <%= form_tag('/tweets', method: :post)  do %>
        <h3>投稿する</h3>
        <input placeholder="Title" type="text" name="title">
        <textarea placeholder="Note" type="text" cols="30" rows="10" name="note"></textarea>
        <input type="submit" value="SENT">
    <% end %>
</div>

app/views/tweets/update.html.erb
<div class="contents row" >
    <div class="success">
        <h3>更新が完了しました。</h3>
        <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @tweets.each do |tweet| %>
      <div class="content_post">
        <%= simple_format(tweet.comment) %>
        <span class="name"><%= tweet.user.nickname %></span>
      </div>
    <% end %>
    <%= paginate(@tweets) %>
  </div>